# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='motivo_consulta',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='paciente',
            name='n_hijos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paciente',
            name='observaciones',
            field=models.CharField(default='', max_length=200),
        ),
    ]
