language: python # => 1

python: # => 2

  - "2.7"

services: # => 3

  - mysql

env: # => 4

  -DJANGO=1.11 DB=mysql
install: # => 5

  - pip install -r dependencias.txt

script: # => 7

  - python manage.py test
