# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0002_auto_20170718_2134'),
        ('paciente', '0002_auto_20170719_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoFisico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('flexiones', models.PositiveSmallIntegerField(default=1)),
                ('sentadillas', models.PositiveSmallIntegerField(default=1)),
                ('saltoLargo', models.PositiveSmallIntegerField(default=1)),
                ('suspension', models.CharField(choices=[('alta', 'alta'), ('media', 'media'), ('baja', 'baja')], default='baja', max_length=200)),
                ('abdomen_bajo', models.PositiveSmallIntegerField(default=1)),
                ('abdomen_alto', models.PositiveSmallIntegerField(default=1)),
                ('espinales', models.PositiveSmallIntegerField(default=1)),
                ('lumbares', models.PositiveSmallIntegerField(default=1)),
                ('trenSuperior', models.TimeField(auto_now_add=True)),
                ('trenInferior', models.TimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paciente.Paciente')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personal.Personal')),
            ],
            options={
                'db_table': 'estadofisico',
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('altura', models.FloatField(default=1.0)),
                ('peso', models.FloatField(default=1.0)),
                ('imc', models.FloatField(default=1.0)),
                ('musculo', models.FloatField(default=1.0)),
                ('grasa_visceral', models.FloatField(default=1.0)),
                ('grasa_porcentaje', models.FloatField(default=1.0)),
                ('cuello', models.FloatField(default=1.0)),
                ('hombros', models.FloatField(default=1.0)),
                ('pecho', models.FloatField(default=1.0)),
                ('brazo_derecho', models.FloatField(default=1.0)),
                ('brazo_izquierdo', models.FloatField(default=1.0)),
                ('antebrazo_derecho', models.FloatField(default=1.0)),
                ('antebrazo_izquierdo', models.FloatField(default=1.0)),
                ('cintura', models.FloatField(default=1.0)),
                ('cadera', models.FloatField(default=1.0)),
                ('muslo_derecho', models.FloatField(default=1.0)),
                ('muslo_izquierdo', models.FloatField(default=1.0)),
                ('pantorrilla_derecha', models.FloatField(default=1.0)),
                ('pantorrilla_izquierda', models.FloatField(default=1.0)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paciente.Paciente')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personal.Personal')),
            ],
            options={
                'db_table': 'ficha',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ficha',
            unique_together=set([('id', 'personal')]),
        ),
        migrations.AlterUniqueTogether(
            name='estadofisico',
            unique_together=set([('id', 'personal')]),
        ),
    ]
