# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 07:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisioterapia', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estadofisico',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='estadofisico',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='estadofisico',
            name='personal',
        ),
        migrations.AddField(
            model_name='ficha',
            name='abdomen_alto',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ficha',
            name='abdomen_bajo',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ficha',
            name='espinales',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ficha',
            name='flexiones',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ficha',
            name='lumbares',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ficha',
            name='saltoLargo',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ficha',
            name='sentadillas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ficha',
            name='suspension',
            field=models.CharField(choices=[('alta', 'alta'), ('media', 'media'), ('baja', 'baja')], default='baja', max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='trenInferior',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='ficha',
            name='trenSuperior',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
        migrations.AlterUniqueTogether(
            name='ficha',
            unique_together=set([]),
        ),
        migrations.DeleteModel(
            name='EstadoFisico',
        ),
    ]
