# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisioterapia', '0002_auto_20170720_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='peso',
            field=models.FloatField(null=True),
        ),
    ]
