# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisioterapia', '0003_auto_20170720_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='altura',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='imc',
            field=models.FloatField(default=1.0, null=True),
        ),
    ]
