# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisioterapia', '0004_auto_20170720_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='musculo',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
