# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisioterapia', '0006_auto_20170720_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='antebrazo_derecho',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='antebrazo_izquierdo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='brazo_derecho',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='brazo_izquierdo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='cadera',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='cintura',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='cuello',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='grasa_porcentaje',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='grasa_visceral',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='hombros',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='imc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='muslo_derecho',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='muslo_izquierdo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='pantorrilla_derecha',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='pantorrilla_izquierda',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='pecho',
            field=models.FloatField(null=True),
        ),
    ]
