# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisioterapia', '0007_auto_20170720_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='suspension',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='baja', max_length=200),
        ),
    ]
