# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisioterapia', '0008_auto_20170720_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='fecha',
        ),
    ]
