# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisioterapia', '0010_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='paciente.Paciente'),
        ),
    ]
