# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ficha_nutricion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('lacteos', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('raravez', 'Rara vez'), ('nunca', 'Nunca')], default='diario', max_length=200)),
                ('vegetales', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('raravez', 'Rara vez'), ('nunca', 'Nunca')], default='semanal', max_length=200)),
                ('frutas', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('raravez', 'Rara vez'), ('nunca', 'Nunca')], default='diario', max_length=200)),
                ('cho', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('raravez', 'Rara vez'), ('nunca', 'Nunca')], default='diario', max_length=200)),
                ('carnes', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('raravez', 'Rara vez'), ('nunca', 'Nunca')], default='diario', max_length=200)),
                ('comidas_rapidas', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('raravez', 'Rara vez'), ('nunca', 'Nunca')], default='diario', max_length=200)),
                ('frituras', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('raravez', 'Rara vez'), ('nunca', 'Nunca')], default='diario', max_length=200)),
                ('enlatados', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('raravez', 'Rara vez'), ('nunca', 'Nunca')], default='diario', max_length=200)),
                ('gaseosas', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('raravez', 'Rara vez'), ('nunca', 'Nunca')], default='diario', max_length=200)),
                ('energizantes', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('raravez', 'Rara vez'), ('nunca', 'Nunca')], default='diario', max_length=200)),
                ('infusiones', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('raravez', 'Rara vez'), ('nunca', 'Nunca')], default='diario', max_length=200)),
                ('lacteos_input', models.CharField(max_length=20)),
                ('vegetales_input', models.CharField(max_length=20)),
                ('frutas_input', models.CharField(max_length=20)),
                ('cho_input', models.CharField(max_length=20)),
                ('carnes_input', models.CharField(max_length=20)),
                ('comidas_rapidas_input', models.CharField(max_length=20)),
                ('frituras_input', models.CharField(max_length=20)),
                ('enlatados_input', models.CharField(max_length=20)),
                ('gaseosas_input', models.CharField(max_length=20)),
                ('energizantes_input', models.CharField(max_length=20)),
                ('infusiones_input', models.CharField(max_length=20)),
                ('pregunta1', models.CharField(max_length=100)),
                ('pregunta2', models.CharField(max_length=100)),
                ('pregunta3', models.CharField(max_length=100)),
                ('pregunta4', models.CharField(max_length=100)),
                ('pregunta5', models.CharField(max_length=100)),
                ('pregunta6', models.CharField(max_length=100)),
                ('proteina', models.PositiveSmallIntegerField()),
                ('grasas', models.PositiveSmallIntegerField()),
                ('carbohidratos', models.PositiveSmallIntegerField()),
                ('dieta', models.CharField(max_length=100)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paciente.Paciente')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personal.Personal')),
            ],
            options={
                'db_table': 'ficha_nutricion',
            },
        ),
    ]
