# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='serie',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
