# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='fecha_vencimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
