# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_auto_20170604_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
