# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0006_auto_20170607_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='serie',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
