# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0007_auto_20170608_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='subtotal',
        ),
    ]
