# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado'),
        ),
        migrations.AddField(
            model_name='personal',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creado'),
            preserve_default=False,
        ),
    ]
