# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalaapp', '0006_auto_20170617_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='usuario/noimagen.jpg', help_text='Foto', null=True, upload_to='usuario/'),
        ),
    ]
