# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kalaapp', '0007_auto_20170617_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado_civil',
            field=models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Viudo', 'Viudo'), ('Divorciado', 'Divorciado')], default='Soltero', max_length=30),
        ),
        migrations.AlterField(
            model_name='rol',
            name='tipo',
            field=models.CharField(choices=[('administrador', 'administrador'), ('paciente', 'paciente'), ('fisioterapista', 'fisioterapista'), ('nutricionista', 'nutricionista'), ('invitado', 'invitado')], default='invitado', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kalaapp.Rol'),
        ),
    ]
