# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico',
            name='fecha',
        ),
    ]
