# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostico',
            old_name='usuario',
            new_name='paciente',
        ),
    ]
