# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0003_remove_diagnosticonutricion_area_afectada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieta',
            name='plan_nut_diario',
        ),
        migrations.AddField(
            model_name='dieta',
            name='descripcion',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='plannutdiario',
            name='dieta',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='diagnostico.Dieta'),
        ),
        migrations.AlterField(
            model_name='plannutdiario',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado')], default='Lunes', max_length=30),
        ),
    ]
