# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0002_auto_20170719_0508'),
        ('diagnostico', '0003_auto_20170718_2203'),
    ]

    operations = [
    ]
