# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0004_auto_20170728_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannutdiario',
            name='dia',
            field=models.CharField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado')], default='Lunes', max_length=30),
        ),
    ]
