# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0006_auto_20170801_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticofisioterapia',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paciente.Paciente'),
        ),
        migrations.AlterField(
            model_name='diagnosticofisioterapia',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personal.Personal'),
        ),
        migrations.AlterField(
            model_name='diagnosticonutricion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paciente.Paciente'),
        ),
        migrations.AlterField(
            model_name='diagnosticonutricion',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personal.Personal'),
        ),
    ]
